version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: go.bug.st/serial
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
  labels:
  - "topic: infrastructure"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - "topic: infrastructure"
