build:
    crosscompilation:
        image: arduino/golang-cross
        auth_config:
            username: $$DOCKER_USERNAME
            password: $$DOCKER_PASSWORD
            email: $$DOCKER_EMAIL
        commands:
            - go get github.com/kardianos/govendor
            - govendor vet +local
            - govendor test +local
            # Linux amd64
            - GOOS=linux GOARCH=amd64 CC=gcc CXX=gcc CGO_ENABLED=1 go build -o artifacts/linux-amd64/arduino-create-agent -ldflags "-X main.git_revision=$$COMMIT"
            - cp config.ini artifacts/linux-amd64
            # Darwin amd64
            - GOOS=darwin GOARCH=amd64 CC=o64-clang CXX=o64-clang CGO_ENABLED=1 go build -o artifacts/osx/arduino-create-agent -ldflags "-X main.git_revision=$$COMMIT"
            - cp config.ini artifacts/osx
            # Windows 386
            - GOOS=windows GOARCH=386 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-gcc CGO_ENABLED=1 go build -o artifacts/windows/arduino-create-agent.exe -ldflags "-H=windowsgui -X main.git_revision=$$COMMIT"
            - cp config.ini artifacts/windows
            - zip -r arduino-create-agent.zip artifacts/*
    linux32:
        image: arduino/golang-linux-32
        commands:
            - GOOS=linux GOARCH=386 CC=gcc CXX=gcc CGO_ENABLED=1 go build -o artifacts/linux-386/arduino-create-agent -ldflags "-X main.git_revision=$$COMMIT"
            - cp config.ini artifacts/linux-386
notify:
    slack:
        webhook_url: $$SLACK_WEBHOOK
        channel: $$SLACK_CHANNEL
        username: drone
        when:
            event: pull_request
        template: |
            {{#success build.status}}
                [{{ repo.name}}] Congrats {{ build.author }}! Your PR works:  {{ build.link_url}}
            {{else}}
                [{{ repo.name}}] Damn {{ build.author }}! Something went wrong with your PR: {{ build.link_url}}
            {{/success}}
publish:
    github_release:
        api_key: $$GITHUB_API_KEY
        files:
            - arduino-create-agent.zip
        checksum:
            - md5
        when:
            event: tag
notify:
    slack:
        webhook_url: $$SLACK_WEBHOOK
        channel: $$SLACK_CHANNEL
        username: drone
        when:
            event: tag
        template: |
            {{#success build.status}}
                [{{ repo.name}}/{{ build.branch }}] A new release is available: {{ build.link_url}}
            {{else}}
                [{{ repo.name}}/{{ build.branch }}] Something went wrong while building a new release: {{ build.link_url}}
            {{/success}}
