// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "arduino-create-agent": Application Resource Href Factories
//
// Command:
// $ main

package app

import (
	"fmt"
	"strings"
)

// CommandsV1Href returns the resource href.
func CommandsV1Href(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/%v", paramid)
}

// UploadV1Href returns the resource href.
func UploadV1Href(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/upload/%v", paramid)
}
