//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package config

import (
	"fmt"
	"os"
	"os/exec"

	"github.com/arduino/go-paths-helper"
	log "github.com/sirupsen/logrus"
)

// getLaunchdAgentPath will return the path of the launchd agent default path
func getLaunchdAgentPath() *paths.Path {
	return GetDefaultHomeDir().Join("Library", "LaunchAgents", "ArduinoCreateAgent.plist")
}

// WritePlistFile function will write the required plist file to $HOME/Library/LaunchAgents/ArduinoCreateAgent.plist
// it will return nil in case of success,
// it will error if the file is already there or in any other case
func WritePlistFile() error {
	src, err := os.Executable()
	if err != nil {
		return err
	}

	launchdAgentPath := getLaunchdAgentPath()

	// For now this file comes from the installbuilder autogenerated one
	launchdAgentDefinition := `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>KeepAlive</key>
		<false/>
		<key>Label</key>
		<string>ArduinoCreateAgent</string>
		<key>ProgramArguments</key>
		<array>
			<string>` + src + `</string>
		</array>
		<key>RunAtLoad</key>
		<true/>

		<key>AbandonProcessGroup</key>
		<true/>
	</dict>
</plist>
`
	if launchdAgentPath.Exist() {
		// TODO check for differences in files(?)
		// we already have an existing launchd plist file, so we don't have to do anything
		return fmt.Errorf("the autostart file %s already exists", launchdAgentPath)
	}
	// we need to create a new one
	return launchdAgentPath.WriteFile([]byte(launchdAgentDefinition))
}

// LoadLaunchdAgent will use launchctl to load the agent, will return an error if something goes wrong
func LoadLaunchdAgent() error {
	oscmd := exec.Command("launchctl", "load", getLaunchdAgentPath().String())
	err := oscmd.Run()
	return err
}

// UnloadLaunchdAgent will use launchctl to load the agent, will return an error if something goes wrong
func UnloadLaunchdAgent() error {
	oscmd := exec.Command("launchctl", "unload", getLaunchdAgentPath().String())
	err := oscmd.Run()
	return err
}

// RemovePlistFile function will remove the plist file from $HOME/Library/LaunchAgents/ArduinoCreateAgent.plist and return an error
// it will not do anything if the file is not there
func RemovePlistFile() error {
	launchdAgentPath := getLaunchdAgentPath()
	if launchdAgentPath.Exist() {
		log.Infof("removing: %s", launchdAgentPath)
		return launchdAgentPath.Remove()
	}
	return nil
}

// TODO win/linux ?
// TODO read the doc about launchd https://www.launchd.info/
