name: Close stale issues
on:
  schedule:
    - cron:  '30 8 * * mon'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: 'This issue has been marked as stale because it has been open 14 days with no activity. Remove stale label or comment, otherwise it will be closed in 7 days '
          close-issue-message: 'This issue has been closed becasue has been stale for 7 days. If you think this issue deserves some attention feel free to reopen it'
          days-before-stale: 14
          days-before-close: 7
          days-before-pr-close: -1
          only-labels: 'waiting for feedback'
          debug-only: false
